export type LegalDocType = 'terms' | 'privacy' | 'health_disclaimer';

export type LegalDocument = {
  docType: LegalDocType;
  version: string;
  title: string;
  contentMd: string;
  isActive: boolean;
};

const VERSION_2025_01_01 = '2025-01-01';

export const LOCAL_LEGAL_DOCUMENTS: LegalDocument[] = [
  {
    docType: 'terms',
    version: VERSION_2025_01_01,
    title: 'Terms of Service',
    isActive: true,
    contentMd: [
      '# Terms of Service',
      '',
      `**Version:** ${VERSION_2025_01_01}`,
      '',
      'These Terms of Service ("Terms") apply to your use of the Calorie Tracker application and related services ("Service"). By creating an account, accessing, or using the Service, you agree to these Terms. If you do not agree, do not use the Service.',
      '',
      '## 1. Eligibility and Accounts',
      '- You must be at least 16 years old (or the minimum age of digital consent in your region) to use the Service.',
      '- You are responsible for maintaining the security of your account credentials and for all activity under your account.',
      '',
      '## 2. No Medical Advice; Assumption of Risk',
      '- The Service is **informational only** and does **not** provide medical, nutritional, or emergency advice.',
      '- The Service is **not a medical device** and is **not regulated** by health authorities.',
      '- Calorie, nutrition, weight, and health estimates are based on assumptions and may be inaccurate.',
      '- You must consult a licensed physician or other qualified professional for medical, nutritional, or fitness advice.',
      '- You assume all risks from using the Service, including the risk of **serious injury or death**. If you have any medical condition or emergency, seek in-person professional care immediately.',
      '',
      '## 3. Safe Use',
      '- Do not use the Service while driving or in any unsafe situation.',
      '- The Service is not for emergency or critical care use.',
      '- You are solely responsible for any actions you take based on the information provided.',
      '',
      '## 4. Acceptable Use',
      '- Do not misuse the Service, interfere with others, or attempt to access it using methods other than the interface provided.',
      '- Do not upload illegal, infringing, or harmful content.',
      '- We may suspend or terminate access for violations of these Terms or to protect users.',
      '',
      '## 5. Content and License',
      '- You retain ownership of content you submit. You grant us a non-exclusive, worldwide license to host, process, and display that content solely to operate and improve the Service.',
      '- We may generate aggregated and de-identified analytics from usage. We do **not** sell personally identifiable information.',
      '',
      '## 6. Privacy',
      '- Our [Privacy Policy](#) explains how we collect, use, and share information. By using the Service, you agree to the Privacy Policy.',
      '',
      '## 7. Changes to the Service',
      '- We may change, suspend, or discontinue the Service (or any part of it) at any time with or without notice.',
      '',
      '## 8. Disclaimers and Limitations of Liability',
      '- The Service is provided **"as is"** and **"as available"** without warranties of any kind.',
      '- To the maximum extent permitted by law, we disclaim all implied warranties, including fitness for a particular purpose, accuracy, and non-infringement.',
      '- To the maximum extent permitted by law, we are **not liable** for any indirect, incidental, special, consequential, or punitive damages, or for loss of data, profits, revenues, business, or goodwill.',
      '- In jurisdictions that do not allow the exclusion or limitation of liability, our liability is limited to the minimum extent permitted by law.',
      '',
      '## 9. Indemnity',
      'You agree to defend and indemnify us against claims, damages, losses, and expenses (including legal fees) arising from your use of the Service or violation of these Terms, to the maximum extent permitted by law.',
      '',
      '## 10. Governing Law and Venue',
      'These Terms are governed by the laws of the Province of Ontario, Canada, without regard to conflict of laws principles. Local mandatory consumer protections still apply. Any disputes will be resolved in the courts located in Toronto, Ontario, unless applicable law requires otherwise.',
      '',
      '## 11. Updates to these Terms',
      'We may update these Terms. When we do, we will update the version date above. Continued use of the Service after the effective date means you accept the updated Terms.',
      '',
      '## 12. Contact',
      'For questions, contact legal@calorietracker.app.',
    ].join('\n'),
  },
  {
    docType: 'privacy',
    version: VERSION_2025_01_01,
    title: 'Privacy Policy',
    isActive: true,
    contentMd: [
      '# Privacy Policy',
      '',
      `**Version:** ${VERSION_2025_01_01}`,
      '',
      'This Privacy Policy explains how we collect, use, and share information when you use the Calorie Tracker application ("Service").',
      '',
      '## 1. Information We Collect',
      '- **Account and contact data:** email, name (if provided), language, and authentication data.',
      '- **Profile and usage data:** height, weight, activity inputs, nutrition logs, goals, device and app settings.',
      '- **Technical data:** device identifiers, OS, app version, and diagnostics.',
      '- **Support interactions:** messages you send to us.',
      '',
      '## 2. How We Use Information',
      '- Provide, operate, and improve the Service.',
      '- Personalize recommendations and estimates.',
      '- Communicate about updates, security, and support.',
      '- Protect against fraud, abuse, or misuse.',
      '- Generate aggregated and **de-identified analytics** to improve the Service. We reserve the right to monetize aggregated insights that do not identify you.',
      '',
      '## 3. Sharing',
      '- **Service providers:** infrastructure, analytics, and support vendors under contractual confidentiality.',
      '- **Legal and safety:** to comply with law or protect rights, safety, or property.',
      '- **No sale of PII:** We **do not sell** personally identifiable information.',
      '',
      '## 4. International Transfers',
      'Data may be processed in countries other than yours. We use appropriate safeguards where required by law.',
      '',
      '## 5. Data Retention',
      'We keep information for as long as needed to provide the Service and comply with legal obligations. You may request deletion, subject to legal limits.',
      '',
      '## 6. Security',
      'We use reasonable technical and organizational measures but cannot guarantee absolute security.',
      '',
      '## 7. Your Rights',
      '- You may access, correct, or delete certain personal data through the app or by contacting us.',
      '- Depending on your region (e.g., EU/UK/EEA), you may have rights to object, restrict processing, or portability. We honor valid requests subject to legal exceptions.',
      '',
      '## 8. Children',
      'The Service is not directed to children under the age of digital consent. If we learn we have collected data from a child without proper consent, we will delete it.',
      '',
      '## 9. Changes to this Policy',
      'We may update this Policy. When we do, we will update the version date above. Continued use means you accept the updated Policy.',
      '',
      '## 10. Contact',
      'Contact us at privacy@calorietracker.app.',
    ].join('\n'),
  },
  {
    docType: 'health_disclaimer',
    version: VERSION_2025_01_01,
    title: 'Health & Medical Disclaimer',
    isActive: true,
    contentMd: [
      '# Health & Medical Disclaimer',
      '',
      `**Version:** ${VERSION_2025_01_01}`,
      '',
      '- The Calorie Tracker app is **not a medical device** and is **not regulated** by any health authority.',
      '- The app provides **informational estimates only** and may be incomplete, incorrect, or based on assumptions.',
      '- The app **does not provide medical advice**, diagnosis, treatment, or emergency services.',
      '- Always consult a licensed physician, dietitian, or other qualified professional before making health, nutrition, or exercise decisions.',
      '- You use the app entirely at your own risk, including the risk of **serious injury or death**.',
      '- If you experience an emergency or concerning symptoms, stop using the app and seek in-person professional care immediately.',
      '- By using the app, you **accept and assume all risks** to the maximum extent permitted by law.',
    ].join('\n'),
  },
];

export function getLocalActiveLegalDocuments(): LegalDocument[] {
  return LOCAL_LEGAL_DOCUMENTS.filter((doc) => doc.isActive);
}

